http_request:
  url: "http://api.lemonban.com/futureloan"
  method: post
  headers: {"X-Lemonban-Media-Type":"lemonban.v2"}

test_data:
  file_name: "case.xlsx"
  sheet_name: "login"

logger:
  name: 'root'
  logger_level: 'DEBUG'
  stream_handler_level: 'DEBUG'
  file: log.log
  file_handler_level: 'INFO'